<!--=========== BEGIN COURSE BANNER SECTION ================-->
    <section id="imgBanner">
      <h2>Course Details</h2>
    </section>
    <!--=========== END COURSE BANNER SECTION ================-->

    
    <!--=========== BEGIN COURSE BANNER SECTION ================-->
    <section id="courseArchive">
      <div class="container">
        <div class="row">
          <!-- start course content -->
          
          <div class="col-lg-8 col-md-8 col-sm-8">
            <?php foreach ($this->category as $cat){ ?>
              <div class="courseArchive_content">              
             <div class="singlecourse_ferimg_area">
               <div class="singlecourse_ferimg">
                 <img src="<?php echo'http://localhost'.$this->baseURL($cat['image'])?>">
               </div>  
                 
                <div class="singlecourse_bottom">
                    <h2><a href="material-type/index/course_id/<?php echo $cat['id'] ?>"><?php echo $cat['course_name']; ?></a></h2> 
                </div>
             </div>
             
                        <!-- start related course -->
          
              </div>
              <!-- End related course -->
            
          
          <!-- End course content -->
<?php } ?>
  
          <!-- start course archive sidebar -->
          
          <!-- start course archive sidebar -->
        </div>
          </div>
      
    </section>
    <!--=========== END COURSE BANNER SECTION ================-->