<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Forms
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Add New Category
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8" style="padding-top: 20px;">
        <?php
        echo $this->form;
        ?>
    </div>
</div>
<!-- /