<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Forms
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Add New Material
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-8" style="padding-top: 20px;">
        <?php
        echo $this->form;
        ?>
    </div>
</div>
<!-- /.row -->
<!--=========== BEGIN CONTACT SECTION ================
    <section id="contact">
      <div class="container">
       <div class="row">
          <div class="col-lg-12 col-md-12"> 
            <div class="title_area">
              <h2 class="title_two">Add new Material To System</h2>
              <span></span> 
              <p>We gave you the abelity to upload your material if it's a document or video or link on Youtube so please follow the constraction to prevent any error's   </p>
            </div>
          </div>
       </div>
       <div class="row">
         <div class="col-lg-10 col-md-10 col-sm-12">
           <div class="contact_form wow fadeInLeft">
               <form class="submitphoto_form" action="" method="POST" enctype="multipart/form-data">
                   <input type="text" class="wp-form-control wpcf5-text" placeholder="Material name=" name="material_name">
                <input type="text" class="wp-form-control wpcf5-email" placeholder="Material Describtion" name="descib">          
                <select class="wp-form-control wpcf5-text" placeholder="Material Type">
                    <option>Video</option>
                    <option>Document</option>
                </select>
                <input type="file" class="wp-form-control wpcf7-text" placeholder="Subject" name="image">
                <textarea class="wp-form-control wpcf7-textarea" cols="30" rows="10" placeholder="What would you like to tell us"></textarea>
                <input type="submit" value="Submit" class="wpcf7-submit">
              </form>
           </div>
         </div>
         <div class="col-lg-4 col-md-4 col-sm-4">
           <div class="contact_address wow fadeInRight">
             <h3>Address</h3>
             <div class="address_group">
               <p>200 Lincoln Ave, Salinas, CA 93901</p>
               <p>Phone: 662-807-9585</p>
               <p>Email:contact@wpfdegree.com</p>
             </div>
             <div class="address_group">
              <ul class="footer_social">
                <li><a href="#" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="Facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="Google+"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#" class="soc_tooltip" title="" data-placement="top" data-toggle="tooltip" data-original-title="Youtube"><i class="fa fa-youtube"></i></a></li>
                </ul>
             </div>
           </div>
         </div>
       </div>
      </div>
    </section>
    =========== END CONTACT SECTION ================-->