<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Categories Control
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Category Control
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->
<div class="col-lg-10">
    <a href="<?php echo $this->baseUrl() . '/admin/addcategory' ?>" type="submit" class="btn btn-md btn-success pull-right" />Add New Category</a>
    <h2>Categories Table</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    
                    <th>Category name</th>
                    <th>Avaliable</th>
                    <th>Action</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <?php foreach ($this->category as $cat) { ?>
                        <td><?php echo $cat['course_name'] ?></td>
                        <?php if($cat['is_active']) 
                            echo ' <td> <input type="checkbox" checked /> </td>';
                       else 
                            echo '<td><input type="checkbox"/></td>';
                       ?> 
                        <td><a href="deletecategory/id/<?php echo $cat['id']; ?>"><span class="glyphicon glyphicon-remove"></a></span></td>
<td><a href="editcategory/id/<?php echo $cat['id']; ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>

                   
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>

</div>

