<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Comments Control
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Comments Control
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->
<div class="col-lg-12">
<h2>Comments Table</h2>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Comment</th>
                <th>username</th> 
                <th>created at</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>

            <?php
            $user_obj= new Application_Model_Users();
            foreach ($this->comments as $comment) {
                  $user_obj->id=$comment['user_id'];
                    $user=$user_obj->getUser();
            	?>
                <tr>
                   <td><?php echo $comment['comment'] ?></td>
                   <?php
                 echo "<td><img class='thumbnail' src='".$this->baseUrl()."/img/user/".$user[0]['image']."' >".$user[0]['username']."</td>"; ?>    
                   <!--  <td><?php //echo $user[0]['image']  ?></td> 
                    <td><?php// echo $user[0]['username']  ?></td> -->
                    <td><?php echo $comment['created_at'] ?></td> 
                    <td><?php echo "<a href='".$this->baseUrl()."/admin/editcomment/id/".$comment['id']."/material_id/".$comment['material_id']."' class='btn btn-md btn-warning'> Edit </a>";?></td>
                    <td><?php echo "<a href='".$this->baseUrl()."/admin/deletecomment/id/".$comment['id']."/material_id/".$comment['material_id']."'class='btn btn-md btn-danger'>Delete</a>"; ?></td>
                    
                </tr>  
                <?php }?>
                <tr><td><?php echo $this->form; ?></td></tr>  
        </tbody>
    </table>
</div>
</div>

