
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Materials Control
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Material Control
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->

<div class="col-lg-7">
    <a href="<?php echo $this->baseUrl() . '/admin/addmaterialtype' ?>" type="submit" class="btn btn-md btn-default pull-right" /><i class="fa fa-fw fa-file-pdf-o"></i> Add New Material Type</a>
<h2>Materials Types Table</h2>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th><i class="fa fa-fw fa-file-pdf-o"></i> Material Type</th>
                <th><i class="fa fa-fw fa-language"></i> Extention</th>
                <th><i class="fa fa-fw fa-clock-o"></i> Created At</th>
                <th><i class="fa fa-fw fa-cogs"></i> Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->materialsTypes as $materialsTypes) { ?>
                <tr>
                    <td><?php echo $materialsTypes['type'] ?></td>
                    <td><?php echo $materialsTypes['material_name'] ?></td>
                    <td><?php echo $materialsTypes['created_at'] ?></td>
                    <td>
                        <!--delete action-->
                        <a type="submit" class="btn btn-md btn-danger" name="delete"  data-toggle="modal" data-target="#typeModal<?php echo $materialsTypes['id'] ?>"/>
                        <i class="fa fa-trash fa-1x"></i> Delete
                        </a>
                        <div class="modal fade" id="typeModal<?php echo $materialsTypes['id'] ?>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Warning</h4>
                                    </div>
                                    <div class="modal-body">

                                        Are you sure you wand to delete material type "<span style="color:green;"><?php echo $materialsTypes['material_name'] ?></span>" !!?
                                    </div>
                                    <div class="modal-footer">
                                        <a href="<?php echo $this->baseUrl() . '/admin/deletematerialtype/id/' . $materialsTypes['id'] ?>" class="btn btn-md btn-danger"> Yes Delete</a>
                                        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--edit action-->
                        <a href="<?php echo $this->baseUrl() . '/admin/editmaterialtype/id/' . $materialsTypes['id'] ?>"data-placement="left" title="Edit This Material Type" class="btn btn-md btn-primary" >
                            <i class="fa fa-pencil-square-o fa-1x"></i> Edit
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
</div>

<script src="<?php echo $this->baseUrl() . '/../public/js/jquery-1.12.3.js' ?>"></script>
<script>
    $(function () {
        console.log('js started');
        $('.btn-group').on('click', function () {
//            console.log($(this).children().children().val());
            var url = $(this).children().children().val();
            window.location.replace(url);

//            $.ajax({
//                url: url,
//                type: 'POST',
//                data: "format=json",
//                async: false,
//                success: function (response) {
////                    var result = JSON.parse(response);
//                    alert(response);
//                },
//                error: function (error) {
//                    console.log(error);
//                }
//            });//end of ajax request

        });




    });

</script>

