<!-- Page Heading -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Materials Control
        </h1>
        <ol class="breadcrumb">
            <li>
                <i class="fa fa-dashboard"></i>  <a href="<?php echo $this->baseUrl() . '/admin' ?>">Dashboard</a>
            </li>
            <li class="active">
                <i class="fa fa-edit"></i> Material Control
            </li>
        </ol>
    </div>
</div>
<!-- /.row -->
<div class="col-lg-12">
    <a href="<?php echo $this->baseUrl() . '/admin/addmaterial' ?>" type="submit" class="btn btn-md btn-success pull-right" />Add New Material</a>
<h2>Materials Table</h2>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Material</th>
                <th>Course</th>
                <th>Image</th>
                <th>Description</th>
                <th>Add Time</th>
                <th>Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>

            <?php foreach ($this->materials as $material) { ?>
                <tr>
                    <td><a href="<?php echo $this->baseUrl() . '/materials_upload_folder/' . $material['material_name'] ?>"><?php echo $material['material_name'] ?></a></td>
                    <td>
                        <?php echo $material['Course'] ?>
                        <input type="button" class="showcat btn btn-sm btn-primary" value=">>" data-toggle="modal" data-target="#myModal" data="<?php echo  $material['CategoryId']  ?>">
                    </td>

                    <td><img src='<?php echo $this->baseUrl() . '/img/materials_images_folder/' . $material['image'] ?>' width='30px' height="20px"></td>
                    <td><?php echo $material['descib'] ?></td>
                    <td><?php echo $material['created_at'] ?></td>
                    <td><?php echo $material['type'] ?></td>

                    <td>
                        <input type="submit" class="btn btn-md btn-danger" name="delete" value="Delete"/>
                        <input type="submit" class="btn btn-md btn-primary" name="active" value="Active"/>
                    </td>
                </tr>
            <?php } ?>

        </tbody>
    </table>
</div>
</div>
<div class="col-lg-7">
    <a href="<?php echo $this->baseUrl() . '/admin' ?>" type="submit" class="btn btn-md btn-success pull-right" />Add New Material Type</a>
<h2>Materials Types Table</h2>
<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Material Type</th>
                <th>Created At</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->materialsTypes as $materialsTypes) { ?>
                <tr>
                    <td><?php echo $materialsTypes['material_name'] ?></td>
                    <td><?php echo $materialsTypes['created_at'] ?></td>
                    <td>
                        <input type="submit" class="btn btn-md btn-danger" name="delete" value="Delete"/>
                        <input type="submit" class="btn btn-md btn-primary" name="active" value="Active"/>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
</div>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                Checkbox is checked
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>
 <script src="<?php echo $this->baseUrl().'/../public/js/jquery-1.12.3.js'?>"></script>
<script>
    $(function(){
        console.log('js started');
        $('.showcat').on('click',function(){
            console.log( $(this).attr('data'));
            
        });
        
    });

</script>

