<br /><br /><br /><br />
<div class="container" style="background-color: white ; height: 500px; padding-top: 15px">
    <table class="table table-responsive" >
        <tr>
            <td rowspan="6"><img src="<?= $this->baseUrl('/img/user/'.$this->user['image']) ?>" height="400px" width="300px"/> </td>
        </tr>
        <tr>
            <td><label for="name">Name : </label></td>
            <td> <font style="size: 25"><?= $this->user['username'] ?> </font> </td>
        </tr>
        <tr>
            <td><label for="email">Email : </label></td>
            <td> <?= $this->user['email'] ?> </td>
        </tr>
        <tr>
            <td><label for="signature">Signature : </label></td>
            <td> <?= $this->user['signature'] ?> </td>
        </tr>
        <tr>
            <td><label for="joined">Joined Since : </label></td>
            <td> <?= $this->user['joined_at'] ?> </td>
        </tr>
        <tr>
            <td><label for="joined">Update : </label></td>
            <td> <a href="<?= $this->baseUrl()?>/user/update-profile" class="btn btn-primary"> Update Profile</a> </td>
        </tr>
    </table>
</div>